version: '3.8'
services:

  test-database:

    image: postgres:14.10
 
    environment:
      POSTGRES_DB: construction_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password



  test-app:
 
    build:
 
      context: .
 
      dockerfile: Dockerfile.test
 
    depends_on:
      - test-database
