version: '3'
services:
  test-database:
    image: postgres:14.10
    environment:
      POSTGRES_DB: construction_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - test-database
    environment:
      - JWT_KEY=${JWT__Key}
      - JWT_ISSUER=${JWT__Issuer}
      - JWT_AUDIENCE=${JWT__Audience}
