# Use the .NET 8 SDK image as the base image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app

# copy the project files
COPY ["construction/construction.csproj", "construction/"]
COPY ["construction.tests/construction.tests.csproj", "construction.tests/"]

# restore the project dependencies
RUN dotnet restore "construction/construction.csproj"
RUN dotnet restore "construction.tests/construction.tests.csproj"

# copy the entire project
COPY . ./

# set testing connection string and environment
ENV ConnectionStrings__TestConnection="Server=test-database;Database=construction_test;User Id=test;Password=password;"
ENV ASPNETCORE_ENVIRONMENT="Testing"

# run the tests
WORKDIR /app/construction.tests
CMD ["dotnet", "test"]
