version: '3'
services:
  test-database:
    image: postgres:14.10
    environment:
      POSTGRES_DB: construction_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - test-database
    environment:
      - JWT__Key=TemporarySuperSecretKeyJustForTestingPurposes!11!!1eleven
      - JWT__Issuer=construction
      - JWT_Audience=construction
