name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4.1.1

      - name: Decrypt appsettings.json
        run: openssl aes-256-cbc -d -in construction/appsettings.json.enc -out construction/appsettings.json -k ${{ secrets.ENCRYPTION_KEY }} -pbkdf2 -iter 100000

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H azureuser@4.234.160.181 >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: krahristov
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t krahristov/construction-backend:latest .
          docker push krahristov/construction-backend:latest


      - name: Copy deployment script

        run: |
          scp -o StrictHostKeyChecking=no Scripts/DeployScriptConstructionBackend.sh azureuser@4.234.160.181:~

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@4.234.160.181 "\
          ls -l ~/DeployScriptConstructionBackend.sh && \
          chmod +x ~/DeployScriptConstructionBackend.sh && \
          bash ~/DeployScriptConstructionBackend.sh"