name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Set Testing Environment
        run: echo "ASPNETCORE_ENVIRONMENT=Testing" >> $GITHUB_ENV

      - name: Set up JWT Secret
        run: echo "Jwt__Key=${{ secrets.JWT_KEY }}" >> $GITHUB_ENV

      - name: Set up JWT Issuer
        run: echo "JWT__Issuer=construction" >> $GITHUB_ENV

      - name: Set up JWT Audience
        run: echo "JWT__Audience=construction" >> $GITHUB_ENV

      - name: Test
        run: docker-compose -f docker-compose.test.yml up --build --exit-code-from test-app
